### ISSUE TITLE
Error with Waterfall

### ISSUE THREAD

**Issue by srnyx** [Tirco/BungeeJoinMessages#4]
Happens whenever someone joins. I'm using the latest Waterfall (I know I am cause I literally just downloaded/installed it).
Doesn't happen on normal Bungeecord.
https://paste.srnyx.xyz/luhomurewu.rb

There's also this warning that is sent before the error, not sure if it's relevant though: https://paste.srnyx.xyz/kadequdixu.properties

**Comment by srnyx** [comment]
@Tirco

**Comment by Tirco** [comment]
ah, yes. I have seen the issue, and I think I know why it happens. Interesting that it only happens on waterfall... The error itself should be harmless, but I can see how the console errors are annoying.

**Comment by srnyx** [comment]
Still getting the errors, here they are together: https://paste.srnyx.xyz/kekucefado.sql

**Comment by srnyx** [comment]
Oh, that's probably why, you hadn't released it yet 🤦‍♂️

**Comment by Tirco** [comment]
Yeahh... I was still looking for bugs in my testing environment. If the issue still happens with you, let me know! :)
